name: Publish to PyPI

on:
  push:
    branches:
      - major  # Or the main branch you use

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Replace with your desired Python version

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Build and package the distribution
      run: |
        python setup.py sdist bdist_wheel

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__  # Replace with your PyPI username
        password: ${{ secrets.PYPI_API_TOKEN }}  # Set up this secret in your GitHub repository settings
        distributions: "sdist bdist_wheel"
